### ISSUE TITLE
Modal Dialog

### ISSUE THREAD

**Issue by michaelgiordanod3** [bitclout/core#1]
Images load at 1000px wide however the css for .modal-dialog is set to a max-width of 500px at the min-width:576px. Updating this to 50% would make the images ideal for non-mobile devices.

**Comment by lazynina** [comment]
This issue appears like it belong on the frontend repo: https://github.com/bitclout/frontend

**Comment by michaelgiordanod3** [comment]
Thank you. Submitted.
