### ISSUE TITLE
BitClout Improvement Proposals

### ISSUE THREAD

**Issue by connerdouglass** [bitclout/core#10]
As BitClout development becomes increasingly community-driven, I believe it is time for the creation of a repository to draft and track **_BitClout Improvement Proposals_** (abbreviated BCIPs).

Overall, the BitClout community is understanding of the need, early on, for the core development team to have very flexible control over the protocol. However, more and more of us in the development community are building real-world businesses on top of the BitClout protocol, and I believe it would be a benefit to everyone if such a BCIP system existed.

This proposal calls for the creation of a repo at **github.com/bitclout/bcips**, similar to the equivalent repo within Bitcoin, [github.com/bitcoin/bips](https://github.com/bitcoin/bips).

Individuals drafting proposals would simply fork the **bitclout/bcips** repo, create a folder and README for their proposal (bcip-001, bcip-002, etc), and submit a pull request back to the **bitclout/bcips** repo. It would be up to the core development team to edit and merge these proposals as they see fit.

These proposals should be limited in scope to the core BitClout protocol, not the backend, frontend, or any other project.

Thank you for your consideration.

**Comment by maebeam** [comment]
Excellent idea, I've been thinking about this over the last week. The real question is should they be called BCIP or CIP?

**Comment by connerdouglass** [comment]
Oh great, a chance for me to be indecisive 😂. Hmm, I'm not attached to BCIP, just used it to paint the picture. CIP has a lot going for it: shorter, more pronounceable. Either one would have my support!

**Comment by dgsus** [comment]
+1 CIP

**Comment by tijno** [comment]
cip +2

**Comment by Mentors4EDU** [comment]
Hi @maebeam 
I tried running a community-version of Clout Improvement Proposals a while back, but it seems to have not been noticed\
Would bitclout mind if I transferred over the repo to your org? That way, it is technically already built w/ issue templates and everything.
https://github.com/Mentors4EDU/BitClout-Proposals

**Comment by bloated-devish** [comment]
> Excellent idea, I've been thinking about this over the last week. The real question is should they be called BCIP or CIP?

I called it CIP (Clout Improvement Proposal) and loosely created it similar to BIP.

Here is my first one. I am hoping this can reside in the doc repo.
https://github.com/bitclout/docs/pull/10

**Comment by maebeam** [comment]
I will make the CIP repo today or tomorrow

**Comment by Mentors4EDU** [comment]
@maebeam If it easier, you can just clone my issue templates w/ the tags or start from scratch depending on what the devs prefer

**Comment by connerdouglass** [comment]
In the spirit of BIP, I hope our CIP repo will focus entirely on the BitClout **protocol**. Not improvements to the BitClout.com website, nor even to a particular implementation of the blockchain.

Thanks @maebeam for taking charge on this!

**Comment by tijno** [comment]
Anything I can do to help to move this forward?

**Comment by dgsus** [comment]
> Anything I can do to help to move this forward?

+1

i would also love to have some clarification on the new developments in regards to the new concensus mechanism, apparently pos is being considered next? i would appreciate to understand if cip's and its voting would be affected under a pos consensus.

cheers!

**Comment by maebeam** [comment]
Sorry for dropping the ball on this everyone. I will create this repo today.

**Comment by tijno** [comment]
Perrrrfect!

**Comment by vbmach** [comment]
> Sorry for dropping the ball on this everyone. I will create this repo today.

Any updates, @maebeam ?

**Comment by maebeam** [comment]
Coming soon!

**Comment by MatanHamilis** [comment]
Love the idea of creating a proposals repo! One thing I had in mind though.
How do you pronounce CIP? Sip? Kip? 
Why not CLIP instead? Or any other abbreviation which is not as prone to mispronounciation?

**Comment by maebeam** [comment]
And launched!
