### ISSUE TITLE
New transactions wont be txindex?

### ISSUE THREAD

**Issue by tijno** [bitclout/core#115]
@redpartyhat @AeonSw4n @diamondhands0 

Was just doing some work to prepare my BQ db schema for the new transactions:

* NFTTransfer
* AcceptNFTTransfer
* BurnNFT
* AuthorizeDerivedKey

But none of these seem to be included yet in `TransactionMetadata` type:

https://github.com/bitclout/core/blob/6fc331f7afa954432d849fb030e6321e28083fa9/lib/db_utils.go#L3253

Also they are not listed in `ComputeTransactionMetadata` func in mempool.

https://github.com/bitclout/core/blob/49d692be508150b9eb681bebdba313f6e8edc222/lib/mempool.go#L1108

Is this intentional and will the associate tx metadata not be returned in the json block output?

**Comment by maebeam** [comment]
TXIndex is deprecated and will be removed once the postgres migration is completed so I wouldn't suggest building anything on top of it.

**Comment by maebeam** [comment]
To actually answer your question though, we don't have any plans to add metadata for these transactions to txindex since it will removed.

**Comment by maebeam** [comment]
To actually answer your question though, we don't have any plans to add metadata for these transactions to txindex since it will removed.

**Comment by tijno** [comment]
thanks @maebeam 

> once the postgres migration is completed

Any idea of when that migration will take place? I know you all have a lot on your plate.
