### ISSUE TITLE
Postgres DB missing tables

### ISSUE THREAD

**Issue by mvanhalen** [bitclout/core#116]
It seems that latest updates for the new transaction types:

NFT_TRANSFER
ACCEPT_NFT_TRANSFER
BURN_NFT

Did not include the tables for Postgres in the migrations  This seems to cause syncing to fail from block 61015 no transactions added and duplication transaction errors occur. Might have a relation with [issue  115](https://github.com/bitclout/core/issues/115)

**Comment by tijno** [comment]
Note first block with NFT_TRANSFER transaction was 61014

**Comment by donhardman** [comment]
How big is postgres now? Just wonder cuz we do not use it.

**Comment by maebeam** [comment]
Thanks for bringing this up, we'll prioritize a fix

**Comment by mvanhalen** [comment]
> How big is postgres now? Just wonder cuz we do not use it.

Like 60 to 70 GB with some extra indexes for faster querying @donhardman

**Comment by AeonSw4n** [comment]
#117 should fix this

**Comment by maebeam** [comment]
Fixed!

**Comment by mvanhalen** [comment]
Awesome! Thanks @AeonSw4n and @maebeam will it automatically update the latest build of the docker image?
