### ISSUE TITLE
Add optional "Sources" field to `SUBMIT_POST` txs

### ISSUE THREAD

**Issue by HPaulson** [bitclout/core#32]
As the BitClout ecosystem expands, and many new applications are built on top of the protocol, having a standard for node-specific content will become vital. For example, if an engineer wanted to create an app built on top of the protocol which only displayed posts meant for that app (For example, if you wanted to make a Reddit-like app, it wouldn't make sense to display all posts from all subreddits on one twitter-like feed), the app could formulate a field like such in the request: `Sources: ["myApp.com"]`. BitClout.com, and any other nodes looking to display all content, could use the `"Default"` source to signify it displays regular content not specific to an application type. Those nodes could filter by this source. This could allow engineers to display posts only allowed for their source, without doing anything too hacky.

While methods for doing this already exist, for example hiding a post by default and making use of `PostExtraData` to identify the source application & if the post is *actually* hidden or not, however, I think having a standard method of doing such would be a much better, and long-lasting, solution.

I think for the long-term success of BitClout we need many types of applications built on top of the protocol, and additions like this would be very very helpful in accomplishing such.

**Comment by tijno** [comment]
Yes! +1 for this 100%.

As an additional use case / considerations.

1) some content that is ok for someone else node, may not be ok for bitclout.com or other nodes.

2) the worst bots/spammers may move to circumvent frontend based methods to stop them (capachas/cloudflare) by running transactions through their own nodes.

Not sure whether there is a way to identify the node that introduced a transaction to the network currently, or whether its possible to do this in a reliable way.

And of course this would also raise the question whether this should at all be possible as this in itself could introduce ways to censor content.

**Comment by HPaulson** [comment]
@tijno Please note the specifics here -- Anyone would be able to add anything to the sources list. If I made a reddit app, and filtered only posts with `cloutsubreddit` in the source, anyone could still create a post on my website through any node -- they'd just have to add the above string in the tx's sources array. A node wouldn't need to be identified whatsoever, nor should we want this -- as it would create censorship (as you mentioned). Such a sources list would act purely as a standard for engineers to make their lives easier and ensure a post is TRULY meant for their app. If another service wants to include a post on their app, they still have the full ability to, just they have to specify that such post is MEANT for their app and that the user wants it there.

**Comment by tijno** [comment]
Yes of course appreciate that. 

Eg default = show all. 

What if the node knows its content is not suitable for general consumption ? Should it not be possible for them to indicate some kind of "opt out", and default nodes opt in if they want it. 

Eg, show me all, apart from nsfw. 

The bot/spam concern is separate completely from this. For separate issue.

**Comment by HPaulson** [comment]
@tijno Quite possibly! Though, it'd have to be based on a gentlemen's handshake. Possibly bitclout.conm & other nodes can have a "NSFW?" box when posting, removing the default flag & adding some other sources. This could also be useful for showing, but blurring, NSFW images.

**Comment by HPaulson** [comment]
Moved to [BitClout/CIPs #3](https://github.com/bitclout/cips/discussions/3)
