### ISSUE TITLE
600 dollars lost and coin price error

### ISSUE THREAD

**Issue by drshenn** [bitclout/core#37]
I bought my own coin for $500. My money disappeared. Also, the token price was a ridiculous number. Can you please solve my problem? @diamondhands @maebeam @craig
@lazynina

![2021-06-17 19_24_40-diamondhands on BitClout - Opera](https://user-images.githubusercontent.com/86081358/122472172-e3f7aa80-cfc8-11eb-9f91-099cffae8a02.png)
![2021-06-17 21_30_12-papatya on BitClout - Opera](https://user-images.githubusercontent.com/86081358/122472184-e823c800-cfc8-11eb-91bc-40570fb97190.png)

0+0+0 = 0.1119 ???

**Comment by maebeam** [comment]
There's already an issue here: #29
