### ISSUE TITLE
Only main.go, no remote_miner_main.go or miner_main files

### ISSUE THREAD

**Issue by Mentors4EDU** [bitclout/core#4]
Hi, running the .sh file creates an error, given that their is no remote_miner_main.go or miner_main files in the core directory.

There are the go commands it should be running:

```
go build remote_miner_main.go && ./remote_miner_main
  --remote_block_producer=https://f07d2458adad0581e6e09ab745c2a258.bitclout.com
  --miner_public_key=BC1YLjJ3FNgo1Q8NU9sEzK3B2obeuq9GvzYr1GnAJgpsVnYCuczcYBe
  --alsologtostderr 
  --v=0
```

However, the files still need to be there for it to build properly.

**Comment by Mentors4EDU** [comment]
Also another quick question, shouldn't the miner_public_key in the 'run.sh' file be changed to the public key of the user mining? Just something I thought worth noting in the documentation.

**Comment by Galanoz** [comment]
go build remote_miner_main.go && ./remote_miner_main \
  --remote_block_producer=https://f07d2458adad0581e6e09ab745c2a258.bitclout.com \
  --miner_public_key=BC1YLjJ3FNgo1Q8NU9sEzK3B2obeuq9GvzYr1GnAJgpsVnYCuczcYBe \
  --alsologtostderr \
  --v=0

**Comment by Mentors4EDU** [comment]
> go build remote_miner_main.go && ./remote_miner_main
> --remote_block_producer=https://f07d2458adad0581e6e09ab745c2a258.bitclout.com
> --miner_public_key=BC1YLjJ3FNgo1Q8NU9sEzK3B2obeuq9GvzYr1GnAJgpsVnYCuczcYBe
> --alsologtostderr
> --v=0

Hi, the `/` was a formatting issue to add new spaces on GitHub, not related to my inquiry.

I was referring to the "no remote_miner_main.go or miner_main files in the core directory" error

**Comment by BarryMode** [comment]
Aye, `remote_miner_main.go` is missing.

**Comment by maebeam** [comment]
https://github.com/bitclout/backend/blob/main/remote_miner_main.go
