### ISSUE TITLE
Remove account from Bitclout

### ISSUE THREAD

**Issue by stonecoldpat** [bitclout/core#5]
Hi,

My old twitter handle @paddypisa has been added to Bitclout's website without my consent:
https://bitclout.com/u/paddypisa

I would like it to be removed please. 

I know this is possible as another account was removed via:
https://www.coindesk.com/bitclouts-alleged-leader-hit-with-cease-and-desist-by-prominent-crypto-law-firm

**Comment by jackeveritt** [comment]
Please remove 

jackeveritt and thndrgames

**Comment by maebeam** [comment]
Please email node.admin@bitclout.com if you'd like your profile to be removed from the bitclout.com node.

**Comment by J-TOBIN** [comment]
Hello,

Do remove profile and photo shown at https://bitclout.com/u/ecwiti

Kind regards,
James

**Comment by maebeam** [comment]
Please email node.admin@bitclout.com if you'd like your profile to be removed from the bitclout.com node.
