### ISSUE TITLE
plan to filter content by movie type PG, PG13, R, X, etc. rating system

### ISSUE THREAD

**Issue by andrewarrow** [bitclout/core#6]
Congrats on the success of this project! I'm still going through all the code but thought I'd submit this... perhaps the start of this already exists?

As a node runner maybe I'd like to only process messages that are NOT R or X rated. A way to vote with my resources, i.e. I'm willing to run a node and help this network but I have my lines of what content I'll process.

And this goes further than just Movie Style ratings, but also politics. As a node runner I might also want to ban certain usernames. Or at least the first step in all this is a way to classify, in great detail, the type of content you are asking the network to process; so the network can give you a bid on that.

For example, I have a pallet of clouts with:

```
178) just normal left leaning user posts
 17) high profile left politic figures
  1) very high profile political figure
```

or:

```
210) normal right leaning user posts
 47) normal left leaning user posts
 15) R or X in nature
```

As a node runner I would want to broker exchanges of pallets with prices for all the various options out there. This is free speech in a decentralized world? There's a market for which node runners will cross what lines. And some of the lines to one group will seem silly and not even a big deal. But just wanted to get thoughts from Clout team on how they are thinking about this...

Another way to say this: Trump could never be banned from the entire clout network, but the % of node owners willing to process him might fluctuate.

**Comment by Mentors4EDU** [comment]
Hi, @andrewarrow aren't you able to implement some variation of content filtering in your own custom code in a node you run?

**Comment by pangia** [comment]
Ya, that is the beauty/idea of the platform. It is a base for you to build what you want. You want porn, make a porn site/app based on bitclout. You want church, make a church site/app.  It is up to you. If you want them to create the filters for you.. then you are back at twitter.

**Comment by Mentors4EDU** [comment]
I personally am against **XXX** rated content and fully support you filtering that if you want, but not on the codebase. Do it in your own code. Once once can filter content in the codebase, others would want to filter other things, and it would become too centralized. There is already an ability to edit the code manually and add filtering and you can still run it as a node connected to BitClout's ecosystem (at least from my understanding).

**Comment by andrewarrow** [comment]
Thanks for the replies! How fascinating to see which forks that do certain types of filtering will be. Yes I could I could fork core today and name it "CleanClout" but then a friend of mine could also fork core but name his "NotSoCleanClout" and his filter logic might be different.

I guess it will come down to money and principals and just general awareness among all the node operators what forks are available.

But sounds like the default that comes from bitclout/core main branch will be no filtering. To @Mentors4EDU 's point of "it would become too centralized" if it came with some opinionated filters.

And I guess once mining kicks in, to make the _most_ money you'll want to not filter anything? By definition limiting the messages you will process limits your potential for profits?

Anyways I'm getting ahead of myself. Tonight I'm just trying to get https://github.com/andrewarrow/clout-cli going. I'm building a CLI to copy the features `identity` and `frontend` are doing now in TypeScript. Just trying to understand how to create a new account, generate a  PublicKeyBase58Check string etc, but do it all from golang not nodejs.

**Comment by maebeam** [comment]
All nodes will process all transactions and then select which content they want to display to users
