### ISSUE TITLE
Multiple users for one account

### ISSUE THREAD

**Issue by CoderDrShen** [bitclout/core#67]
Gradually, corporate companies started to open Bitclout accounts. In these companies, the personnel responsible for social media manage the account. This situation creates a problem. If the employee is malicious, it can damage the account. It can steal all the funds in the account. I think there should be a multi-user feature. And the authority of these accounts should be restricted. (authority to manage the fund, send diamonds, send messages, edit bio)

**Comment by tijno** [comment]
As per my comment on the other issue - please use the new CIP process for this. https://github.com/bitclout/cips
