### ISSUE TITLE
Hacked accounts

### ISSUE THREAD

**Issue by CoderDrShen** [bitclout/core#68]
Currently, Bitclout has very few users. But after the marketing efforts, millions of users will join us in a short time. And that will bring some problems. One of them is the possibility of hacking accounts. In this case, users should be able to protect their own account. my suggestions;
- Account migration feature just like reserve accounts
- change seed words
- one more layer of security can be added

**Comment by tijno** [comment]
Valid points for discussion for sure. But please move this to the discussion area in github.com/bitclout/cips - which is the right place for discussing things like this.
