### ISSUE TITLE
Sync issues - Problem located

### ISSUE THREAD

**Issue by 2000c5** [bitclout/core#9]
Many people are complaining that different versions of Bitclout will not sync.

I experienced this issue using the recent releases (not run), so I deleted my data to try to resync:

If you delete your node data and try a fresh resync it will fail at block #7651 every time and not go beyond that.

E0520 14:47:50.001408 29894 blockchain.go:1073] MarkBlockInvalid: Block height: 7651, Block hash: 000000000055e730dfdd449306fd8a94aaa4d09f612d34ba288022331346c391, Error: ConnectBlock: : ConnectTransaction: : RuleErrorBitcoinExchangeBlockHashNotFoundInMainBitcoinChain

All sync errors seem to be caused by this BTC check.

I manually edited the code to ignore the BTC check (temporary) and was able to fully sync.

Hope this info helps!

**Comment by maebeam** [comment]
Thanks for the report. Fixed in 1eec8b2d4bddbe45f01831137a8fdda2986d9d81
