### ISSUE TITLE
postgres exception RuleErrorInsufficientFundsForNFTBid on block 46923

### ISSUE THREAD

**Issue by Zyther** [bitclout/core#99]
running with the following params: 

```
./backend run \
  --glog-v=2 \
  --glog-vmodule="*bitcoin_manager*=2,*balance*=2,*view*=2,*frontend*=2,*peer*=0,*addr*=0,*network*=0,*utils*=0,*connection*=0,*main*=0,*server*=2,*mempool*=2,*miner*=2,*blockchain*=2" \
  --num-mining-threads=0  \
  --max-block-templates-cache=0 \
  --txindex=true \
  --miner-public-keys=BC1YLg4sz2dEa81Zhw3ktsrEMKRz5J9ucxAczoZrM3zZRPgMoCGJM7r \
  --starter-bitclout-seed='REDACTED' \
  --data-dir=/mnt/d/data_dirs/n0_1  \
  --block-cypher-api-key=REDACTED \
  --min-satoshis-for-profile=0 \
  --postgres-uri="postgres://REDACTED@REDACTED/postgres" \
  --connect-ips="35.232.92.5:17000" \
```

E0823 10:49:25.105978    1883 blockchain.go:1218] MarkBlockInvalid: Block height: 46923, Block hash: 0000000000005c3002b1182c37678c887f08cfb6017eb45fae09d83ffcf7e608, Error: ConnectBlock: : ConnectTransaction: : RuleErrorInsufficientFundsForNFTBid
E0823 10:49:25.106013    1883 blockchain.go:1219] MarkBlockInvalid: Printing stack trace so error is easy to find: 
E0823 10:49:25.106056    1883 blockchain.go:1220] goroutine 40 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa5
github.com/bitclout/core/lib.(*Blockchain).MarkBlockInvalid(0xc0586b4000, 0xc06a04b400, 0xc18a60f900, 0x49)
        /home/alecg/src/discoverclout/core/lib/blockchain.go:1220 +0x205
github.com/bitclout/core/lib.(*Blockchain).ProcessBlock(0xc0586b4000, 0xc187678e10, 0xc1ec663d00, 0x0, 0x0, 0x0)
        /home/alecg/src/discoverclout/core/lib/blockchain.go:1935 +0x270b
github.com/bitclout/core/lib.(*Server)._handleBlock(0xc0586a8000, 0xc0d5598900, 0xc187678e10)
        /home/alecg/src/discoverclout/core/lib/server.go:1178 +0x6a5
github.com/bitclout/core/lib.(*Server)._handlePeerMessages(0xc0586a8000, 0xc1882821c0)
        /home/alecg/src/discoverclout/core/lib/server.go:1481 +0x291
github.com/bitclout/core/lib.(*Server).messageHandler(0xc0586a8000)
        /home/alecg/src/discoverclout/core/lib/server.go:1521 +0x2d4
created by github.com/bitclout/core/lib.(*Server).Start
        /home/alecg/src/discoverclout/core/lib/server.go:1697 +0xcf
E0823 10:49:25.106131    1883 blockchain.go:1227] MarkBlockInvalid: Not marking blocks invalid for now because it makes debugging easier
E0823 10:49:25.106166    1883 server.go:1126] Server._handleBlock: Encountered an error processing block <Header: < 46923, 0000000000005c3002b1182c37678c887f08cfb6017eb45fae09d83ffcf7e608, 1 >, Signer Key: BC1YLh768bVj2R3QpSiduxcvn7ipxF3L3XHsabZYtCGtsinUnNrZvNN>. Disconnecting from peer [ Remote Address: 35.232.92.5:17000 PeerID=20 ]: Error while processing block: : ConnectBlock: : ConnectTransaction: : RuleErrorInsufficientFundsForNFTBid

**Comment by tijno** [comment]
Yep seen 2 others get stuck here too:  @dharmeshs and smartalec

**Comment by Zyther** [comment]
I am smartalec @tijno  ;)

**Comment by tijno** [comment]
Haha 😂 @Zyther

**Comment by maebeam** [comment]
Thanks! Just merged a fix for this.

**Comment by tijno** [comment]
@maebeam does it need clear of DB and resync to get past the error ? I am still seeing it in my updated backend (using latest image published 10min ago)

**Comment by maebeam** [comment]
Theoretically it would not require a resync but it unfortunately might

**Comment by tijno** [comment]
Ok. Thx @maebeam resyncing already. 

ps. are some pg_balances during sync supposed to be negative?

**Comment by maebeam** [comment]
> ps. are some pg_balances during sync supposed to be negative?

This is definitely concerning, thanks for highlighting this.

**Comment by tijno** [comment]
thats what i thought. 

![20210824-p0Cd6Grp](https://user-images.githubusercontent.com/69529928/130610742-24854438-9b7b-4e16-9423-9d5a3c1e1085.png)
